# docker-compose.yml
version: '3.8'

services:
  bot-trader-v2:
    build: .
    restart: unless-stopped
    ports:
      # Mapeia a porta externa 8080 para a porta interna 8080 do container
      - "8080:8080"
    environment:
      # Aqui você pode definir as variáveis de ambiente para o Docker Compose
      # Mas no EasyPanel, você as definirá na interface gráfica
      - IQ_EMAIL=${IQ_EMAIL}
      - IQ_PASSWORD=${IQ_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - ENTRY_PERCENTAGE=${ENTRY_PERCENTAGE}
      - WINS_TO_LEVEL_UP=${WINS_TO_LEVEL_UP}
      - LOSS_COMPENSATION=${LOSS_COMPENSATION}