# docker-compose.yml
version: '3.8'

services:
  bot-trader:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - IQ_EMAIL=${IQ_EMAIL}
      - IQ_PASSWORD=${IQ_PASSWORD}
      - ENTRY_PERCENTAGE=${ENTRY_PERCENTAGE:-3.0}
      - GERENCIAMENTO_PERCENT=${GERENCIAMENTO_PERCENT:-5.0}
    volumes:
      - ./logs:/app/logs